services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: flask_db
      MYSQL_USER: flask_user
      MYSQL_PASSWORD: flask_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: ./backend/
    restart: always
    depends_on:
      - mysql
    volumes:
      - ./backend:/app
    ports:
      - "3000:6000"
    environment:
      FLASK_ENV: development
      SQLALCHEMY_DATABASE_URI: mysql+pymysql://flask_user:flask_password@mysql/flask_db

  web_app:
    build: ./web_app/
    restart: always
    depends_on:
      - backend
    volumes:
      - ./web_app:/app
    ports:
      - "80:6000"
    environment:
      FLASK_ENV: development

  adminer:
    image: adminer:latest
    environment:
      ADMINER_DEFAULT_SERVER: mysql
    ports:
      - 8080:8080

  nginx:
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web_app

volumes:
  mysql_data:
